create_theme:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: fx_luxor
    name:
      required: true
      example: Party
      selector:
        text: {}
    letter:
      example: B
      selector:
        text: {}
    groups:
      selector:
        object:
          multiple: true
          label_field: entity_id
          description_field: brightness_pct
          translation_key: theme_group
          fields:
            entity_id:
              required: true
              selector:
                entity:
                  integration: fx_luxor
                  domain: light
            brightness_pct:
              required: true
              selector:
                number:
                  min: 0
                  max: 100
                  step: 1
                  unit_of_measurement: '%'
                  mode: slider
            color_slot:
              selector:
                number:
                  min: 0
                  max: 260
                  step: 1
                  mode: box

save_current_as_theme:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: fx_luxor
    theme:
      example: Nighttime
      selector:
        text: {}
    name:
      example: Evening
      selector:
        text: {}
    letter:
      example: C
      selector:
        text: {}
    lights:
      selector:
        entity:
          integration: fx_luxor
          domain: light
          multiple: true

update_theme:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: fx_luxor
    theme:
      required: true
      example: Nighttime
      selector:
        text: {}
    groups:
      required: true
      selector:
        object:
          multiple: true
          label_field: entity_id
          description_field: brightness_pct
          translation_key: theme_group
          fields:
            entity_id:
              required: true
              selector:
                entity:
                  integration: fx_luxor
                  domain: light
            brightness_pct:
              required: true
              selector:
                number:
                  min: 0
                  max: 100
                  step: 1
                  unit_of_measurement: '%'
                  mode: slider
            color_slot:
              selector:
                number:
                  min: 0
                  max: 260
                  step: 1
                  mode: box

rename_theme:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: fx_luxor
    theme:
      required: true
      example: Nighttime
      selector:
        text: {}
    name:
      required: true
      selector:
        text: {}

delete_theme:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: fx_luxor
    theme:
      required: true
      example: Nighttime
      selector:
        text: {}
